// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Text.Json.Serialization;

namespace RepasoParcialCine.Entities
{
    public partial class Genero
    {
        public Genero()
        {
            Peliculas = new HashSet<Pelicula>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        [JsonIgnore]
        public virtual ICollection<Pelicula> Peliculas { get; set; }
    }
}